{{- range .Values.secrets }}
{{- if not (.existingSecretName) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .name }}
  labels:
    {{- include "jni1-poc.labels" $ | nindent 4 }}
data:
  {{- range .values }}
  {{ .name }}: {{ .value | quote | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
