version: "3.9"

services:
  mongo:
    image: mongo:5.0.10
    container_name: mongo
    # Provide mongo config
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: mongoPassword
    # Maps tcp port to host
    ports:
      - 27017:27017
    volumes:
      - mongo-data-5.0.10:/data/db
    networks:
      - basyx-java-server-sdk
      
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongoAdmin:mongoPassword@mongo:27017
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - 8086:8081
    networks:
      - basyx-java-server-sdk
    depends_on:
      - mongo
      
  aas-env:
    image: eclipsebasyx/aasenvironment:1.0.0
    container_name: aas-env
    volumes:
      - /home/ubuntu/jni1/jni1-pocv1-backend/basyx.aasenvironment/basyx.aasenvironment.component/src/main/resources/application.properties:/application/application.properties
    # enable this line to map the aas model file from your local machine to the docker image. update also the config file of the aas-environment component <application.properties> and set the filePath to upload in basyx.environment attribute.
    #  - /home/ubuntu/jni1/jni1-pocv1-backend/basyx.aasenvironment/basyx.aasenvironment.component/src/test/resources/testEnvironment.json:/application/testEnvironment.json
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongoAdmin:mongoPassword@mongo:27017/aasenvironments?authSource=admin
    ports:
      - 8081:8081
    networks:
      - basyx-java-server-sdk
    depends_on:
      - mongo
      - mqtt
        
  aas-registry:
    image: eclipsebasyx/aas-registry-log-mongodb:1.0.0
    container_name: aas-registry
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongoAdmin:mongoPassword@mongo:27017
#    volumes:
#      - ./aas-registry.yml:/workspace/config/application.yml
    networks:
      - basyx-java-server-sdk
    depends_on:
      - mongo
    restart: always

  aas-web-ui_v2:
    image: eclipsebasyx/assgui:1.0.0
    container_name: aas-web-ui_v2
    ports:
      - 80:3001
    environment:
      VITE_REGISTRY_PATH: "http://192.168.211.155:8080/api/v3.0"
      VITE_SUBMODEL_REGISTRY_PATH: ""
      VITE_AAS_SERVER_PATH: "http://192.168.211.155:8081"
    restart: always
    
  mqtt:
    image: eclipse-mosquitto:2.0.15
    container_name: mqtt
    ports:
      - 1884:1884
    volumes:
      - ./mosquitto:/mosquitto/config
    
  databridge:
    image: eclipsebasyx/databridge:1.0.0
    container_name: databridge-device-integration
    ports:
      - 8090:8090
    volumes:
      - ./databridge:/usr/share/config
      #- ./databridge-mqtt:/usr/share/config
      #- ./databridge-http-delegator:/usr/share/config
      #- ./databridge-timer:/usr/share/config
    depends_on:
      - aas-env
      - mqtt
    networks:
      - basyx-java-server-sdk

volumes:
  mongo-data-5.0.10:
    driver: local
    
networks:
  basyx-java-server-sdk:
    name: basyx-java-server-sdk
    driver: bridge
    internal: false
    
